/* Header file generated by fdesign on Fri Nov  6 08:05:26 2009 */

#ifndef FD_gui_h_
#define FD_gui_h_

#include <forms.h>

/* Callbacks, globals and object handlers */

extern void callback_file( FL_OBJECT *, long );
extern void callback_edit( FL_OBJECT *, long );
extern void callback_view( FL_OBJECT *, long );
extern void callback_calc( FL_OBJECT *, long );
extern void callback_baseline( FL_OBJECT *, long );
extern void callback_measure( FL_OBJECT *, long );
extern void callback_peak( FL_OBJECT *, long );
extern void callback_simulate( FL_OBJECT *, long );
extern void callback_graph( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * gui;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * file;
    FL_OBJECT * edit;
    FL_OBJECT * spectrum;
    FL_OBJECT * view;
    FL_OBJECT * calc;
    FL_OBJECT * baseline;
    FL_OBJECT * measure;
    FL_OBJECT * peak;
    FL_OBJECT * simulate;
    FL_OBJECT * speed;
    FL_OBJECT * endor_field;
    FL_OBJECT * triple_freq;
    FL_OBJECT * scans;
    FL_OBJECT * mprog;
    FL_OBJECT * graph;
} FD_gui;

extern FD_gui * create_form_gui( void );

#endif /* FD_gui_h_ */
