/* Form definition file generated by fdesign */

#include <stdlib.h>
#include "param.h"


/***************************************
 ***************************************/

FD_params *
create_form_params( void )
{
    FL_OBJECT *obj;
    FD_params *fdui = fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->params = fl_bgn_form( FL_NO_BOX, 815, 600 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 815, 600, "" );

    fdui->file = obj = fl_add_input( FL_NORMAL_INPUT, 60, 40, 700, 30, "File" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->name = obj = fl_add_input( FL_NORMAL_INPUT, 60, 90, 320, 30, "Name" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->operator = obj = fl_add_input( FL_NORMAL_INPUT, 440, 90, 320, 30, "Opr." );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    obj = fl_add_text( FL_NORMAL_TEXT, 260, 10, 240, 20, "Spectrum parameters" );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );

    fdui->temp = obj = fl_add_input( FL_NORMAL_INPUT, 245, 190, 70, 30, "Temp (K)" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->date = obj = fl_add_input( FL_NORMAL_INPUT, 75, 190, 110, 30, "Date" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->scans = obj = fl_add_input( FL_NORMAL_INPUT, 360, 190, 60, 30, "Scans" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->gain = obj = fl_add_input( FL_NORMAL_INPUT, 265, 290, 110, 30, "Gain" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->moda = obj = fl_add_input( FL_NORMAL_INPUT, 265, 340, 110, 30, "ModA. (G)" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->modf = obj = fl_add_input( FL_NORMAL_INPUT, 75, 340, 110, 30, "ModF (kHz)" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->power = obj = fl_add_input( FL_NORMAL_INPUT, 682, 340, 110, 30, "MW Power (mW)" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->freq = obj = fl_add_input( FL_NORMAL_INPUT, 465, 340, 110, 30, "MW Freq (GHz)" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->cf = obj = fl_add_input( FL_NORMAL_INPUT, 75, 390, 110, 30, "CF (G)" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->sw = obj = fl_add_input( FL_NORMAL_INPUT, 75, 440, 110, 30, "SW (G)" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->type = obj = fl_add_choice( FL_NORMAL_CHOICE, 635, 190, 110, 30, "Type" );

    fdui->units = obj = fl_add_choice( FL_NORMAL_CHOICE, 75, 490, 110, 30, "Units" );

    fdui->accept = obj = fl_add_button( FL_NORMAL_BUTTON, 240, 550, 100, 30, "Accept" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    fdui->cancel = obj = fl_add_button( FL_NORMAL_BUTTON, 440, 550, 100, 30, "Cancel" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    fdui->resolution = obj = fl_add_choice( FL_NORMAL_CHOICE, 265, 440, 110, 30, "Resolution" );

    fdui->endor_b = obj = fl_add_input( FL_NORMAL_INPUT, 265, 390, 110, 30, "ENDOR B (G)" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->time = obj = fl_add_input( FL_NORMAL_INPUT, 75, 240, 110, 30, "Time" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->solvent = obj = fl_add_input( FL_NORMAL_INPUT, 240, 240, 380, 30, "Solvent" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->timec = obj = fl_add_input( FL_NORMAL_INPUT, 465, 290, 110, 30, "Time const. (s)" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->ctime = obj = fl_add_input( FL_NORMAL_INPUT, 682, 290, 110, 30, "Conv. time (s)" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->endor_mod = obj = fl_add_input( FL_NORMAL_INPUT, 465, 390, 110, 30, "ENDOR ModA." );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->endor_pump_freq = obj = fl_add_input( FL_NORMAL_INPUT, 682, 390, 110, 30, "TRIPLE freq. (MHz)" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->endor_power = obj = fl_add_input( FL_NORMAL_INPUT, 465, 440, 110, 30, "ENDOR pwr (dB)" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->triple_power = obj = fl_add_input( FL_NORMAL_INPUT, 682, 440, 110, 30, "TRIPLE pwr (dB)" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->theta = obj = fl_add_input( FL_NORMAL_INPUT, 265, 490, 110, 30, "Theta (rad)" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->phi = obj = fl_add_input( FL_NORMAL_INPUT, 465, 490, 110, 30, "Phi (rad)" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->sphase = obj = fl_add_input( FL_NORMAL_INPUT, 682, 490, 110, 30, "Signal phase" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->info = obj = fl_add_input( FL_NORMAL_INPUT, 60, 140, 700, 30, "Info" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->harmonic = obj = fl_add_input( FL_NORMAL_INPUT, 685, 240, 110, 30, "Harmonic" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->resonator = obj = fl_add_input( FL_NORMAL_INPUT, 75, 285, 110, 30, "Reson" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->delay = obj = fl_add_input( FL_NORMAL_INPUT, 475, 190, 80, 30, "Delay (s)" );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    obj = fl_add_text( FL_NORMAL_TEXT, 400, 410, 40, 20, "(kHz)" );

    fl_end_form( );

    fdui->params->fdui = fdui;

    return fdui;
}
