/* Header file generated by fdesign on Mon Nov  2 10:23:34 2009 */

#ifndef FD_params_h_
#define FD_params_h_

#include <forms.h>

/* Callbacks, globals and object handlers */



/* Forms and Objects */

typedef struct {
    FL_FORM   * params;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * file;
    FL_OBJECT * name;
    FL_OBJECT * operator;
    FL_OBJECT * temp;
    FL_OBJECT * date;
    FL_OBJECT * scans;
    FL_OBJECT * gain;
    FL_OBJECT * moda;
    FL_OBJECT * modf;
    FL_OBJECT * power;
    FL_OBJECT * freq;
    FL_OBJECT * cf;
    FL_OBJECT * sw;
    FL_OBJECT * type;
    FL_OBJECT * units;
    FL_OBJECT * accept;
    FL_OBJECT * cancel;
    FL_OBJECT * resolution;
    FL_OBJECT * endor_b;
    FL_OBJECT * time;
    FL_OBJECT * solvent;
    FL_OBJECT * timec;
    FL_OBJECT * ctime;
    FL_OBJECT * endor_mod;
    FL_OBJECT * endor_pump_freq;
    FL_OBJECT * endor_power;
    FL_OBJECT * triple_power;
    FL_OBJECT * theta;
    FL_OBJECT * phi;
    FL_OBJECT * sphase;
    FL_OBJECT * info;
    FL_OBJECT * harmonic;
    FL_OBJECT * resonator;
    FL_OBJECT * delay;
} FD_params;

extern FD_params * create_form_params( void );

#endif /* FD_params_h_ */
