/* Form definition file generated by fdesign */

#include <stdlib.h>
#include "spec_setup.h"


/***************************************
 ***************************************/

FD_spec_setup *
create_form_spec_setup( void )
{
    FL_OBJECT *obj;
    FD_spec_setup *fdui = fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->spec_setup = fl_bgn_form( FL_NO_BOX, 630, 509 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 630, 509, "" );

    fdui->mod_freq = obj = fl_add_input( FL_NORMAL_INPUT, 170, 295, 90, 30, "EPR: Mod. freq." );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->mod_max = obj = fl_add_input( FL_NORMAL_INPUT, 290, 295, 90, 30, "" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    obj = fl_add_text( FL_NORMAL_TEXT, 290, 260, 90, 30, "Mod. max" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );

    fdui->signal_phase_max = obj = fl_add_input( FL_NORMAL_INPUT, 395, 295, 90, 30, "" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    obj = fl_add_text( FL_NORMAL_TEXT, 395, 260, 90, 30, "Signal 0o" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );

    fdui->signal_phase_min = obj = fl_add_input( FL_NORMAL_INPUT, 500, 295, 90, 30, "" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    obj = fl_add_text( FL_NORMAL_TEXT, 500, 260, 90, 30, "Signal 90o" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );

    fdui->ok = obj = fl_add_button( FL_NORMAL_BUTTON, 100, 455, 90, 30, "OK" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    fdui->cancel = obj = fl_add_button( FL_NORMAL_BUTTON, 220, 455, 90, 30, "Cancel" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    fdui->load = obj = fl_add_button( FL_NORMAL_BUTTON, 340, 455, 90, 30, "Load" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    fdui->save = obj = fl_add_button( FL_NORMAL_BUTTON, 460, 455, 90, 30, "Save" );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    fdui->sigchanid = obj = fl_add_input( FL_NORMAL_INPUT, 520, 50, 40, 30, "GPIB ID" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->magnetid = obj = fl_add_input( FL_NORMAL_INPUT, 520, 125, 40, 30, "GPIB ID" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->mwid = obj = fl_add_input( FL_NORMAL_INPUT, 210, 50, 40, 30, "GPIB ID" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->rfid = obj = fl_add_input( FL_NORMAL_INPUT, 520, 195, 40, 30, "GPIB ID" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->mwcounter = obj = fl_add_choice( FL_NORMAL_CHOICE2, 20, 50, 110, 30, "" );

    fdui->sigchan = obj = fl_add_choice( FL_NORMAL_CHOICE2, 325, 50, 110, 30, "" );

    fdui->gaussmeter = obj = fl_add_choice( FL_NORMAL_CHOICE2, 20, 125, 110, 30, "" );

    fdui->magnet = obj = fl_add_choice( FL_NORMAL_CHOICE2, 325, 125, 110, 30, "" );

    fdui->endorunit = obj = fl_add_choice( FL_NORMAL_CHOICE2, 20, 200, 110, 30, "" );

    fdui->gaussmeterid = obj = fl_add_input( FL_NORMAL_INPUT, 210, 125, 40, 30, "GPIB ID" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->rfcounter = obj = fl_add_choice( FL_NORMAL_CHOICE2, 325, 195, 110, 30, "" );

    fdui->endorid = obj = fl_add_input( FL_NORMAL_INPUT, 210, 195, 40, 30, "GPIB ID" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->endor_mod_freq = obj = fl_add_input( FL_NORMAL_INPUT, 170, 340, 90, 30, "ENDOR: Mod. freq." );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->endor_mod_max = obj = fl_add_input( FL_NORMAL_INPUT, 290, 340, 90, 30, "" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->endor_signal_phase_max = obj = fl_add_input( FL_NORMAL_INPUT, 395, 340, 90, 30, "" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->endor_signal_phase_min = obj = fl_add_input( FL_NORMAL_INPUT, 500, 340, 90, 30, "" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    obj = fl_add_text( FL_NORMAL_TEXT, 20, 10, 260, 30, "MW counter" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );

    obj = fl_add_text( FL_NORMAL_TEXT, 325, 10, 260, 30, "Signal channel" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );

    obj = fl_add_text( FL_NORMAL_TEXT, 20, 85, 260, 30, "Gaussmeter" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );

    obj = fl_add_text( FL_NORMAL_TEXT, 325, 85, 260, 30, "Magnet control" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );

    obj = fl_add_text( FL_NORMAL_TEXT, 20, 160, 260, 30, "ENDOR unit" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );

    obj = fl_add_text( FL_NORMAL_TEXT, 325, 160, 260, 30, "RF counter" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );

    fdui->comment = obj = fl_add_input( FL_NORMAL_INPUT, 110, 390, 480, 40, "Comments" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_return( obj, FL_RETURN_END_CHANGED );

    fdui->verbose = obj = fl_add_checkbutton( FL_PUSH_BUTTON, 20, 250, 180, 40, "Verbose" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );

    fl_end_form( );

    fdui->spec_setup->fdui = fdui;

    return fdui;
}
