/* Header file generated by fdesign on Fri Oct 30 15:47:26 2009 */

#ifndef FD_spec_setup_h_
#define FD_spec_setup_h_

#include <forms.h>

/* Callbacks, globals and object handlers */



/* Forms and Objects */

typedef struct {
    FL_FORM   * spec_setup;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * mod_freq;
    FL_OBJECT * mod_max;
    FL_OBJECT * signal_phase_max;
    FL_OBJECT * signal_phase_min;
    FL_OBJECT * ok;
    FL_OBJECT * cancel;
    FL_OBJECT * load;
    FL_OBJECT * save;
    FL_OBJECT * sigchanid;
    FL_OBJECT * magnetid;
    FL_OBJECT * mwid;
    FL_OBJECT * rfid;
    FL_OBJECT * mwcounter;
    FL_OBJECT * sigchan;
    FL_OBJECT * gaussmeter;
    FL_OBJECT * magnet;
    FL_OBJECT * endorunit;
    FL_OBJECT * gaussmeterid;
    FL_OBJECT * rfcounter;
    FL_OBJECT * endorid;
    FL_OBJECT * endor_mod_freq;
    FL_OBJECT * endor_mod_max;
    FL_OBJECT * endor_signal_phase_max;
    FL_OBJECT * endor_signal_phase_min;
    FL_OBJECT * comment;
    FL_OBJECT * verbose;
} FD_spec_setup;

extern FD_spec_setup * create_form_spec_setup( void );

#endif /* FD_spec_setup_h_ */
